package tela;

import derivada.DerivadaQuociente;
import derivada.DerivadaSoma;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

// @author VINICIUS
public class TelaPrincipal extends javax.swing.JFrame {

    private DerivadaSoma soma;
    private DerivadaQuociente quociente;
    private ArrayList<DerivadaSoma> somaLista;
    private ArrayList<DerivadaQuociente> quocienteLista;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.soma = new DerivadaSoma();
        this.quociente = new DerivadaQuociente();
        this.somaLista = new ArrayList<>();
        this.quocienteLista = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSoma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextF = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFL = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Derivadas");

        jButtonSoma.setText("Soma");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jTextF.setColumns(20);
        jTextF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextF.setRows(5);
        jScrollPane1.setViewportView(jTextF);

        jButton1.setText("Quociente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFL.setColumns(20);
        jTextFL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFL.setRows(5);
        jScrollPane2.setViewportView(jTextFL);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("F(x)");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("F'(x)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonSoma)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSoma)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        // TODO add your handling code here:
        String aparecer = "";
        String aparecerL = "";
        this.limpar();
        this.abriSoma();
        for (int i = 0; i < this.getSomaLista().size(); i++) {
            this.setSoma(this.getSomaLista().get(i));
            this.getSoma().derivar();
            if (i == 0) {
                aparecer += this.getSoma().getFx().getFuncao() + "\n";
                aparecerL += this.getSoma().getfLinhax().getFuncao() + "\n";
                System.out.println(this.getSoma().getfLinhax().juntar());
            } else {
                aparecer += "\n" + this.getSoma().getFx().getFuncao() + "\n";
                aparecerL += "\n" + this.getSoma().getfLinhax().getFuncao() + "\n";
            }
        }
        this.jTextF.setText(aparecer);
        this.jTextFL.setText(aparecerL);
    }//GEN-LAST:event_jButtonSomaActionPerformed

    public void abriSoma() {
        String nome = "src/derivada/soma.txt";
        try {
            FileReader arq = new FileReader(nome);
            BufferedReader lerArq = new BufferedReader(arq);
            String linha = lerArq.readLine();

            while (linha != null) {
                this.getSoma().getFx().setFuncao(linha.trim());
                this.getSomaLista().add(this.getSoma());

                linha = lerArq.readLine();
                this.soma = new DerivadaSoma();

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        String aparecer = new String();
        String aparecerL = new String();
        this.limpar();
        this.abriQuociente();
        for (int i = 0; i < this.getQuocienteLista().size(); i++) {
            this.setQuociente(this.getQuocienteLista().get(i));
            this.getQuociente().dividir();
            if (i == 0) {
                aparecer += this.getQuociente().getfOriginal().getFuncao() + "\n";
                aparecerL += this.getQuociente().getfLinhaOriginal().getFuncao() + "\n";
            } else {
                aparecer += "\n" + this.getQuociente().getfOriginal().getFuncao() + "\n";
                aparecerL += "\n" + this.getQuociente().getfLinhaOriginal().getFuncao() + "\n";
            }
            this.quociente = new DerivadaQuociente();
        }
        this.jTextF.setText(aparecer);
        this.jTextFL.setText(aparecerL);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void abriQuociente() {
        String nome = "src/derivada/quociente.txt";
        String funcao = new String();
        try {
            FileReader arq = new FileReader(nome);
            BufferedReader lerArq = new BufferedReader(arq);
            String linha = lerArq.readLine();

            while (linha != null) {
                this.getQuociente().getfOriginal().setFuncao(linha.trim());
                this.getQuocienteLista().add(this.getQuociente());
                this.quociente = new DerivadaQuociente();
                linha = lerArq.readLine();

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void limpar() {
        this.soma = new DerivadaSoma();
        this.quociente = new DerivadaQuociente();
        this.somaLista = new ArrayList<>();
        this.quocienteLista = new ArrayList<>();
        this.jTextF.setText(null);
        this.jTextFL.setText(null);
    }

    public DerivadaSoma getSoma() {
        return soma;
    }

    public void setSoma(DerivadaSoma soma) {
        this.soma = soma;
    }

    public DerivadaQuociente getQuociente() {
        return quociente;
    }

    public void setQuociente(DerivadaQuociente quociente) {
        this.quociente = quociente;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextF;
    private javax.swing.JTextArea jTextFL;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the somaLista
     */
    public ArrayList<DerivadaSoma> getSomaLista() {
        return somaLista;
    }

    /**
     * @param somaLista the somaLista to set
     */
    public void setSomaLista(ArrayList<DerivadaSoma> somaLista) {
        this.somaLista = somaLista;
    }

    /**
     * @return the quocienteLista
     */
    public ArrayList<DerivadaQuociente> getQuocienteLista() {
        return quocienteLista;
    }

    /**
     * @param quocienteLista the quocienteLista to set
     */
    public void setQuocienteLista(ArrayList<DerivadaQuociente> quocienteLista) {
        this.quocienteLista = quocienteLista;
    }
}
